python train_subg.py \
--data_path data/VoxCeleb/voxceleb.pkl \
--model_filename checkpoint/voxceleb_sampler6.pth \
--knn_k 10 \
--levels 3 \
--faiss_gpu \
--hidden 256 \
--epochs 100 \
--lr 0.01 \
--batch_size 2048 \
--num_conv 1 \
--balance  \
--gat
