python train_subg_split200.py \
--data_path data/VoxCeleb/split/split20/ \
--model_filename checkpoint/voxceleb_split_20_10_2_n_s.pth \
--knn_k 10 \
--levels 2 \
--faiss_gpu \
--hidden 256 \
--epochs 200 \
--lr 0.01 \
--batch_size 1024 \
--num_conv 1 \
--balance  \
--use_cluster_feat
